import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/page";
import Navbar from "@/components/moreOptions/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SyncWave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-rows h-full">
          <div className="w-1/5 h-full">
            <Navbar/>
          </div>
          <main className="flex-1 h-full ">{children}</main> 
        </div>
       
      </body>
    </html>
  );
}
